version: '3.x'

services:
  boj-green-service:
    container_name: boj-green-container
    image: synoti21/baekjoon-bot:latest
    env_file:
      - env.list
    volumes:
      - ubuntu_log_volume:/app/logs

  boj-blue-service:
    container_name: boj-blue-container
    image: synoti21/baekjoon-bot:latest
    env_file:
      - env.list
    volumes:
      - ubuntu_log_volume:/app/logs
volumes:
  ubuntu_log_volume:
    external: true