name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v3.8.1
      with:
        node-version: "18.x"

    - name: Generate ENV file
      run: |
        echo "DISCORD_TOKEN=$DISCORD_TOKEN" >> .env
        echo "RDS_ENDPOINT=$RDS_ENDPOINT" >> .env
        echo "RDS_USER=$RDS_USER" >> .env
        echo "RDS_PASSWORD=$RDS_PASSWORD" >> .env
        echo "RDS_DB=$RDS_DB" >> .env
        echo "BASE_URL=$BASE_URL" >> .env
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        RDS_ENDPOINT: ${{ secrets.RDS_ENDPOINT }}
        RDS_USER: ${{ secrets.RDS_USER }}
        RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
        RDS_DB: ${{ secrets.RDS_DB }}
        BASE_URL: ${{ secrets.BASE_URL }}

    - name: npm ci
      run: npm ci

    - name: Run Jest
      run: npm test

    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        logout: false
        
    - name: build and release to DockerHub
      run: |
        docker build -t ${{ secrets.PROJECT_NAME }} .
        docker tag ${{ secrets.PROJECT_NAME }}:latest ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.PROJECT_NAME }}:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.PROJECT_NAME }}:latest
    
      
